#!/bin/sh

# Use neovim for vim if present.
#[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	gca="git commit -a" \
	smi="sudo make install"\
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"
	..="cd .."

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport"

#manage dotfiles with git bare repos
alias \
	gdf="/usr/bin/git --git-dir=$HOME/.bare-repos/dotfiles --work-tree=/" \
	git-snp="/usr/bin/git --git-dir=$HOME/.bare-repos/snippets --work-tree=/"

#connect to my bluetooth devices
alias \
	amazon="bluetoothctl power off; bluetoothctl power on; bluetoothctl connect A0:E9:DB:01:D0:EF" \
	anker="bluetoothctl power off; bluetoothctl power on; bluetoothctl connect AC:12:2F:2A:9E:DD"

#delete background images i dont like
#alias \
#	rmbg="rm $(readlink '/home/daniel/.local/share/bg') && setbg /home/daniel/pics/bg"


alias \
	df='df -h' \
	free='free -m' \
	np='nano -w PKGBUILD' \
	more=less \
	pp="ps -aux | grep" \
	ll="ls -lha --color=auto" \
	l="ll" \
	plz="sudo" \
	cl="clear" \
	med="vim '+normal Go' ~/pers/med/bs-bp.tsv" \
	cll="clear && ls -lha" \
#alias gt="gotop -c monokai -S 3 -r 500ms --mbps" \
	gt="gotop -S 3 -r 500ms --mbps" \
	dpdf="mupdf -C d0d0d0 -I" \

#wireguard
alias wq="wg-quick"
alias wqu="wg-quick up mullvad-de4"
alias wqd="wg-quick down mullvad-de4"

#make new dir and navigate to it
nd ()
{
  mkdir -p -- "$1" &&
  cd -P -- "$1"
}

#set displays
alias \
	tereza="/home/daniel/.screenlayout/tereza.sh; /home/daniel/.local/bin/setbg" \
	schoepf="/home/daniel/.screenlayout/schoepf24.sh; /home/daniel/.local/bin/setbg"
alias soso="sudo swapoff -a && sudo swapon -a"

#for docker and docker-compose
alias \
	dcu="docker compose up -d" \
	dcd="docker compose stop" \
	dcr="docker compose up -d --force-recreate" \
	vd="vim docker-compose.yml"

dn() {
  mkdir $1
  cd $1
  vim docker-compose.yml
}
