#!/bin/bash

#place this into /etc/NetworkManager/dispatcher.d
#set the 2 variables below to the correct values
#make sure the "enp0s*" is the correct network interface for you, or adapt! (use: "ip a")

VPN_NAME="vpn" #VPN connection Name according to NetworkManager (as in /etc/NetworkManager/system-connections/)
UUID="9mdn0wnq-098b-9hbs-19js-nas989j2ndsb" #uuid, found with 'nmcli connection show "$CONNECTION-NAME"'

interface=$1 status=$2
case $status in
  up|vpn-down)
  [ $(nmcli connection show | grep 'enp0s*' | awk '{print $2}') == $UUID ] && nmcli connection up id "$VPN_NAME"
    ;;
  down)
    [ $(nmcli connection show | grep 'enp0s*' | awk '{print $2}') == $UUID ] && nmcli connection show --active | grep "$VPN_NAME" && nmcli connection down id "$VPN_NAME"
    ;;
esac
